### ISSUE TITLE
When deleting sample content provided by distro totals for Status is not updated

### ISSUE THREAD

**Issue by carlosmirandalevy** [markaspot/mark-a-spot#45]
Deleting all sample content, properly resets all category counters to zero.
But resulting 'Status' for both 'Open' and 'Closed' is '1'.

![screen shot 2017-03-11 at 5 32 30 pm](https://cloud.githubusercontent.com/assets/277457/23824953/11533fc8-0681-11e7-94fc-abf02d178b17.png)

**Comment by markaspot** [comment]
Thanks for pointing at this issue. Investigating seems to lead to d.o [paragraph/entity_reference_revision issue](https://www.drupal.org/node/2741937) there.

**Comment by markaspot** [comment]
This has been fixed in 8.4.x
