### ISSUE TITLE
markaspot_static_json.module error when finishing install

### ISSUE THREAD

**Issue by carlosmirandalevy** [markaspot/mark-a-spot#46]
Installing a clean profile on Ubuntu 16.04 Apache MPM-event / PHP7 Fastcgi or Mac OS Apache with PHP5 displays the following error at the end of the installation procedure, after entering site information. The error goes away and does not return anymore:

_- Warning: file_get_contents(public://requests.json): failed to open stream: "Drupal\Core\StreamWrapper\PublicStream::stream_open" call failed in markaspot_static_json_request() (line 85 of modules/contrib/markaspot_static_json/markaspot_static_json.module)._
```
markaspot_static_json_request() (Line: 62)
markaspot_static_json_cron()
call_user_func_array('markaspot_static_json_cron', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('markaspot_static_json', 'cron') (Line: 223)
Drupal\Core\Cron->invokeCronHandlers() (Line: 122)
Drupal\Core\Cron->run() (Line: 75)
Drupal\Core\ProxyClass\Cron->run() (Line: 1778)
install_finished(Array) (Line: 662)
install_run_task(Array, Array) (Line: 540)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)
```
![screen shot 2017-03-11 at 6 16 05 pm](https://cloud.githubusercontent.com/assets/277457/23825270/e4f107e8-0686-11e7-91d0-2e93705e7b62.png)

**Comment by markaspot** [comment]
The cron should run immediately after setup. Or catch the exception in repo of [markaspot_static_json](https://github.com/markaspot/markaspot_static_json) Will address this soon.

**Comment by markaspot** [comment]
Fixed by https://github.com/markaspot/markaspot_static_json/commit/50d33ae3fb6f4a839ecabd38017d2865e8e87e6f
