### ISSUE TITLE
Outdated version for leaflet in composer.json breaks install/update

### ISSUE THREAD

**Issue by carlosmirandalevy** [markaspot/mark-a-spot#52]
Install/Update via composer fails due to outdated version of leaflet being required on composer.json:

```
composer install
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for markaspot/markaspot_map dev-8.x-3.x -> satisfiable by markaspot/markaspot_map[dev-8.x-3.x].
    - markaspot/markaspot_map dev-8.x-3.x requires leaflet-mas/leaflet 1.0.3 -> no matching package found.
```

Updating leaflet from 1.0.2 to 1.0.3 on composer.json, fixes this:
line 22 & 25
```
            "type": "package",
            "package": {
                "name": "leaflet-mas/leaflet",
                "version": "v1.0.3",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/Leaflet/Leaflet/archive/v1.0.3.zip",
                    "type": "zip"
                }
```

line 228
`        "leaflet-mas/leaflet": "1.0.3",`

**Comment by markaspot** [comment]
This should be resolved by now: https://github.com/markaspot/mark-a-spot/blob/master/composer.json#L22

**Comment by MickeyBG** [comment]
I downloaded the last version of markaspot and i have this error message ¿Any Idea?

` composer install
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositorUpdating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - markaspot/markaspot_map 8.3.0-beta1 requires leaflet-mas/leaflet 1.0.2 -> no matching package found.
    - markaspot/markaspot_map 8.3.0-alpha1 requires leaflet/leaflet 1.0.1 -> no matching package found.
    - Installation request for markaspot/markaspot 8.3.0 -> satisfiable by markaspot/markaspot[8.3.0].
    - markaspot/markaspot 8.3.0 requires markaspot/markaspot_map >8@dev -> satisfiable by markaspot/markaspot_map[8.3.0-alpha1, 8.3.0-beta1, 8.3.0-rc1, 8.3.0-rc2, dev-master].
    - markaspot/markaspot_map 8.3.0-rc1 requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - markaspot/markaspot_map 8.3.0-rc2 requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - markaspot/markaspot_map dev-master requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - Conclusion: don't install drupal/search_api 1.x-dev

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`
