### ISSUE TITLE
Issues of Custom Categories not displayed on map

### ISSUE THREAD

**Issue by re031014** [markaspot/mark-a-spot#57]
Service request can be submitted with custom category, but no location is assigned to it and is not marked on map.

**Comment by markaspot** [comment]
I can not reproduce this.  Are there any hints in the logs? Javascript errors?

**Comment by markaspot** [comment]
Set up an installation simplytest.me, removed WKT from validation, added a category, added a request. See screenshot attached.
<img width="962" alt="Mas-Screenshot custom category" src="https://user-images.githubusercontent.com/212898/30708261-7e4e73a2-9efe-11e7-9bdb-083c061ee72a.png">

**Comment by re031014** [comment]
The only difference between your setup and the one I am using is that I am hosting mine on a private server and not using the test platform. I have also attached a screenshot after clicking the zoom out button several times. If I am doing something wrong, I am more than happy to provide information to troubleshoot. Logs show no problems and there are no Javascript errors. 

![image](https://user-images.githubusercontent.com/31998267/30709371-fdd78642-9ecf-11e7-9a6a-e4f734150485.png)

**Comment by markaspot** [comment]
This looks like a leaflet problem or config error, so I would classify this as a support request. A problem that can't be reproduced is not always a bug. I would have to look into your installation to help you.
