### ISSUE TITLE
Composer installation breaks!

### ISSUE THREAD

**Issue by MickeyBG** [markaspot/mark-a-spot#58]
I downloaded the last version and i have this error message ¿Any Idea?

` composer install
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositorUpdating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - markaspot/markaspot_map 8.3.0-beta1 requires leaflet-mas/leaflet 1.0.2 -> no matching package found.
    - markaspot/markaspot_map 8.3.0-alpha1 requires leaflet/leaflet 1.0.1 -> no matching package found.
    - Installation request for markaspot/markaspot 8.3.0 -> satisfiable by markaspot/markaspot[8.3.0].
    - markaspot/markaspot 8.3.0 requires markaspot/markaspot_map >8@dev -> satisfiable by markaspot/markaspot_map[8.3.0-alpha1, 8.3.0-beta1, 8.3.0-rc1, 8.3.0-rc2, dev-master].
    - markaspot/markaspot_map 8.3.0-rc1 requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - markaspot/markaspot_map 8.3.0-rc2 requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - markaspot/markaspot_map dev-master requires drupal/search_api 1.x-dev -> satisfiable by drupal/search_api[1.x-dev].
    - Conclusion: don't install drupal/search_api 1.x-dev

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

**Comment by markaspot** [comment]
Please try again. Could not reproduce this after the latest [commit](https://github.com/markaspot/markaspot_map/commit/e5b6cf21b937cfce8feed7f17254767b128c1851).
