### ISSUE TITLE
Cannot apply patch for drupal/page_manager 

### ISSUE THREAD

**Issue by Sunia88** [markaspot/mark-a-spot#71]
Cannot apply patch for drupal/page_manager-https://www.drupal.org/files/issues/2918564-22.patch, a got this error during installation, and then cause failure instalation

**Comment by markaspot** [comment]
Hi, could you please try to update the markaspot-profile? I just released [8.4.2](https://github.com/markaspot/markaspot/releases/tag/8.4.2) which should solve this issue.

**Comment by Sunia88** [comment]
is this need mark-a-spot files? how to use this?

**Comment by markaspot** [comment]
not sure, if I really get you. Please just update [this line](https://github.com/markaspot/mark-a-spot/blob/282d28e671a8188921b6364d20187de2b77871df/composer.json#L51) in your composer.json. After that you run composer update.

**Comment by Sunia88** [comment]
sorry, I am just newbee on drupal 8, don't know how to update profile drupal base :)

**Comment by markaspot** [comment]
No Problem. Just proceed [as described](https://github.com/markaspot/mark-a-spot/issues/71#issuecomment-405015954).

**Comment by Sunia88** [comment]
![image](https://user-images.githubusercontent.com/11264819/42726031-606b458a-87c0-11e8-9ef4-98684aba1aef.png)

I change the line to "markaspot/markaspot": "^8.4.2", and run composer update. what I miss?

**Comment by Sunia88** [comment]
Thank you for yaour suggest, I am able to install, but then I get this error, what I should do for this?
![image](https://user-images.githubusercontent.com/11264819/42730702-b9764c16-882d-11e8-953b-379e203f818e.png)

**Comment by Sunia88** [comment]
thank you very much for your advise, the error was gone, I just have to copy this shariff distribution, to [root drupal]\web\libraries\sheriff, and the error gone
