### ISSUE TITLE
Recommended mobile app (Android)?

### ISSUE THREAD

**Issue by poVoq** [markaspot/mark-a-spot#72]
There seem to be various 311 compatible mobile apps, but none that sticks out as especially recent or fully featured. Is there any one that is recommended to be used with Mark-a-Spot? 

If there is one that is open-source and/or offline capable that would be awesome.

Thanks for sharing :)

**Comment by markaspot** [comment]
I haven’t tested anything but the GeoReporter App. Check out https://github.com/City-of-Bloomington/open311-android

**Comment by poVoq** [comment]
Hmm, that one is ancient though...

Maybe this one could work?
https://github.com/CodeTanzania/open311-android
