### ISSUE TITLE
some plugins not working and it does not load map tiles. also updates error out with ajax 500 error

### ISSUE THREAD

**Issue by ghost** [markaspot/mark-a-spot#78]
Hi there,

i installed on Ubuntu 20.04 installation went through without errors and ist is accessible. But it does not load any map tiles, updates are not available and it says some modules are not working.

Do i need to use an old version of Ubuntu because it is form 2018? or am i missing anything?

**Comment by markaspot** [comment]
Thanks for using it. Pleease switch to the `dev` [branch](https://github.com/markaspot/mark-a-spot/blob/8.5.x-dev/composer.json) (using the 8.x-5.x-dev branch of the [actual distribution package](https://github.com/markaspot/markaspot).

**Comment by markaspot** [comment]
As there hasn't been any recent activity and the issue appears to be resolved or no longer relevant, I'm closing this for housekeeping purposes. Please feel free to reopen it if you have further comments or new information to add.
