### ISSUE TITLE
Dependency Exception when installing

### ISSUE THREAD

**Issue by dieter-s** [markaspot/mark-a-spot#87]
When installing on Debian 12 (Nginx Webserver, PHP 8.2) from the dev-Branch, either using the web installer or drush, the install fails with an UnmetDependenciesException.

Followed the instructions from https://docs.markaspot.de/en/latest/installation/.

composer install/update was run before - so everything shound be installed?

Output from drush on the cli:
```
 [notice] Performed install task: install_bootstrap_full

In UnmetDependenciesException.php line 100:

  Configuration objects provided by <em class="placeholder">service_request</em> have unmet dependencies: <em class="placeholder">core.ent
  node.service_request.management (field_group, geolocation_nominatim), core.entity_view_display.node.service_request.teaser (markaspot_gr [...]
```

Output from webserver error.log:

```
FastCGI sent in stderr: "PHP message: Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">service_request</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.node.service_request.default (geolocation_nominatim), core.entity_form_display.node.service_request.management (field_group, geolocation_nominatim), core.entity_view_display.node.service_request.teaser (markaspot_group, field_formatter_class)</em> in /opt/markaspot/web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php on line 100 #0 /opt/markaspot/web/core/lib/Drupal/Core/Config/ConfigInstaller.php(527): Drupal\Core\Config\UnmetDependenciesException::create()
#1 /opt/markaspot/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall()
#2 /opt/markaspot/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(199): Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall()
#3 /opt/markaspot" while reading response header from upstream

```

standard drupal 10 installation is working on the machine.

What installation method is recommended for production use? Github readme mentions docker deployment for dev purposes.

Thanks for any hints or help.

**Comment by markaspot** [comment]
Yeah, i need to unlink the old installation guide, please follow the docker based setup from the [readme.md](https://github.com/markaspot/mark-a-spot)

**Comment by dieter-s** [comment]
Thanks for the quick reply, will try to use the docker deployment.

**Comment by markaspot** [comment]
I hope you could resolved the issue. I've identified and fixed several bugs in the recent releases and am now working to simplify the setup process. Please feel free to re-open the issue.
